version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DB_NAME: cinema_db
      DB_USER: your_db_user
      DB_PASS: your_db_password
      DB_HOST: db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data: